"""add Department

Revision ID: 394e08e11137
Revises: a18bf46346f2
Create Date: 2025-09-10 15:01:42.555592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394e08e11137'
down_revision = 'a18bf46346f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
