"""rename department

Revision ID: 95abe9935666
Revises: 394e08e11137
Create Date: 2025-09-10 15:07:08.905985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95abe9935666'
down_revision = '394e08e11137'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###